export type PropertyTag =
  "stem-diameter" | "height-crown" | "qsm-branches-biomass" | "leaf-wood" | "tree-stem-detection";

export type DataInput = "TLS" | "MLS" | "ULS" | "ALS" | "Photogrammetry";

export interface Method {
  id: string;
  name: string;
  authors: string;
  summary: string;
  repo: string; // full url
  homepage?: string;
  paper?: string;
  language: string;
  license: string;
  properties: PropertyTag[];
  inputs: DataInput[];
  year: number;
  featured?: boolean;
}

export const PROPERTY_LABELS: Record<PropertyTag, string> = {
  "stem-diameter": "Stem diameter",
  "height-crown": "Height & crown",
  "qsm-branches-biomass": "QSM / branches / biomass",
  "leaf-wood": "Leaf-wood classification",
  "tree-stem-detection": "Tree & stem detection",
};

export const METHODS: Method[] = [
  {
    id: "treeqsm",
    name: "TreeQSM",
    authors: "Raumonen et al.",
    summary:
      "Reconstruction of quantitative structure models of trees from point cloud data. The de-facto reference for cylinder-based QSMs.",
    repo: "https://github.com/InverseTampere/TreeQSM",
    paper: "https://doi.org/10.3390/rs5020491",
    language: "MATLAB",
    license: "GPL-3.0",
    properties: ["qsm-branches-biomass", "stem-diameter"],
    inputs: ["TLS", "MLS"],
    year: 2013,
    featured: true,
  },
  {
    id: "adtree",
    name: "AdTree",
    authors: "Du et al.",
    summary:
      "Accurate, detailed, and automatic modelling of laser-scanned trees producing skeleton + branch geometry.",
    repo: "https://github.com/tudelft3d/AdTree",
    paper: "https://doi.org/10.3390/rs11182074",
    language: "C++",
    license: "GPL-3.0",
    properties: ["qsm-branches-biomass"],
    inputs: ["TLS"],
    year: 2019,
    featured: true,
  },
  {
    id: "tls2trees",
    name: "TLS2Trees",
    authors: "Wilkes et al.",
    summary:
      "Scalable tree segmentation pipeline for forest-scale TLS point clouds. Includes semantic + instance segmentation.",
    repo: "https://github.com/philwilkes/TLS2trees",
    paper: "https://doi.org/10.1111/2041-210X.14233",
    language: "Python",
    license: "GPL-3.0",
    properties: ["tree-stem-detection", "leaf-wood"],
    inputs: ["TLS"],
    year: 2023,
    featured: true,
  },
  {
    id: "fsct",
    name: "FSCT",
    authors: "Krisanski et al.",
    summary:
      "Forest Structural Complexity Tool - deep-learning semantic segmentation and DBH/stem metrics from high-resolution point clouds.",
    repo: "https://github.com/SKrisanski/FSCT",
    paper: "https://doi.org/10.3390/rs13224677",
    language: "Python",
    license: "BSD-3-Clause",
    properties: ["stem-diameter", "height-crown", "tree-stem-detection", "leaf-wood"],
    inputs: ["TLS", "MLS"],
    year: 2021,
    featured: true,
  },
  {
    id: "3dfin",
    name: "3DFin",
    authors: "Laino et al.",
    summary:
      "Automatic dendrometry (DBH, stem position, height) from TLS/MLS with a friendly desktop GUI and CLI.",
    repo: "https://github.com/3DFin/3DFin",
    homepage: "https://pypi.org/project/3DFin/",
    paper: "https://doi.org/10.1016/j.envsoft.2024.106004",
    language: "Python",
    license: "GPL-3.0",
    properties: ["stem-diameter", "height-crown", "tree-stem-detection"],
    inputs: ["TLS", "MLS"],
    year: 2023,
  },
  {
    id: "simpleforest",
    name: "SimpleForest",
    authors: "Hackenberg et al.",
    summary:
      "QSM modelling plugin for Computree with segmentation and cylinder fitting for forest plots.",
    repo: "https://github.com/SimpleForest/pluginSimpleForest",
    homepage: "http://simpleforest.org",
    language: "C++",
    license: "GPL-3.0",
    properties: ["qsm-branches-biomass", "stem-diameter"],
    inputs: ["TLS"],
    year: 2015,
  },
  {
    id: "treeiso",
    name: "TreeIso",
    authors: "Xi & Hopkinson",
    summary:
      "Individual tree isolation from TLS point clouds using a bottom-up cut-pursuit segmentation.",
    repo: "https://github.com/truebelief/artemis_treeiso",
    paper: "https://doi.org/10.3390/rs14236116",
    language: "Python",
    license: "MIT",
    properties: ["tree-stem-detection"],
    inputs: ["TLS"],
    year: 2022,
  },
  {
    id: "forestsemantic",
    name: "ForAINet",
    authors: "Xiang et al.",
    summary:
      "Deep learning framework for panoptic segmentation of forest point clouds into individual trees and semantic classes.",
    repo: "https://github.com/prs-eth/PanopticSegForLargeScalePointCloud",
    paper: "https://doi.org/10.1016/j.isprsjprs.2023.12.014",
    language: "Python",
    license: "MIT",
    properties: ["tree-stem-detection", "leaf-wood"],
    inputs: ["TLS", "MLS", "ALS"],
    year: 2024,
  },
  {
    id: "lidr",
    name: "lidR",
    authors: "Roussel et al.",
    summary:
      "R package for airborne LiDAR data manipulation with individual tree detection, segmentation, and canopy metrics.",
    repo: "https://github.com/r-lidar/lidR",
    homepage: "https://r-lidar.github.io/lidRbook/",
    paper: "https://doi.org/10.1016/j.rse.2020.112061",
    language: "R",
    license: "GPL-3.0",
    properties: ["height-crown", "tree-stem-detection"],
    inputs: ["ALS", "ULS"],
    year: 2015,
    featured: true,
  },
  {
    id: "pytreedb",
    name: "pytreedb",
    authors: "Weiser et al.",
    summary:
      "Python library and DB for single-tree LiDAR point-cloud datasets, useful as input to structural methods.",
    repo: "https://github.com/3dgeo-heidelberg/pytreedb",
    paper: "https://doi.org/10.1016/j.softx.2022.101073",
    language: "Python",
    license: "MIT",
    properties: ["tree-stem-detection"],
    inputs: ["TLS", "MLS", "ULS"],
    year: 2022,
  },
  {
    id: "raycloudtools",
    name: "raycloudtools",
    authors: "Lowe et al. (CSIRO)",
    summary:
      "Ray-based point cloud toolkit with tree extraction, trunk detection, and forest structural analysis.",
    repo: "https://github.com/csiro-robotics/raycloudtools",
    paper: "https://doi.org/10.1109/ACCESS.2021.3084954",
    language: "C++",
    license: "BSD-3-Clause",
    properties: ["tree-stem-detection", "qsm-branches-biomass", "stem-diameter"],
    inputs: ["MLS", "TLS"],
    year: 2021,
  },
  {
    id: "leafwoodsep",
    name: "LeWoS",
    authors: "Wang et al.",
    summary:
      "Leaf-wood classification of TLS point clouds using recursive segmentation - unsupervised, widely used baseline.",
    repo: "https://github.com/dwang520/LeWoS",
    paper: "https://doi.org/10.1111/2041-210X.13342",
    language: "MATLAB",
    license: "MIT",
    properties: ["leaf-wood"],
    inputs: ["TLS"],
    year: 2020,
  },
  {
    id: "treetool",
    name: "TreeTool",
    authors: "Montoya et al.",
    summary:
      "Fast automatic tree detection and DBH estimation tool for forest inventory from TLS point clouds.",
    repo: "https://github.com/porteratzo/TreeTool",
    paper: "https://doi.org/10.1016/j.softx.2021.100889",
    language: "Python",
    license: "MIT",
    properties: ["tree-stem-detection", "stem-diameter"],
    inputs: ["TLS"],
    year: 2021,
  },
  {
    id: "point2tree",
    name: "point2tree",
    authors: "Wielgosz et al.",
    summary:
      "End-to-end pipeline for tree segmentation and structural parameter extraction from high-density LiDAR.",
    repo: "https://github.com/SmartForest-no/point2tree",
    paper: "https://doi.org/10.3390/rs15153737",
    language: "Python",
    license: "MIT",
    properties: ["tree-stem-detection", "stem-diameter", "leaf-wood"],
    inputs: ["MLS", "TLS", "ULS"],
    year: 2023,
  },
  {
    id: "tlseparation",
    name: "TLSeparation",
    authors: "Vicari et al.",
    summary:
      "Python library to separate wood and leaf points in TLS scans, precursor to QSM building.",
    repo: "https://github.com/TLSeparation/source",
    paper: "https://doi.org/10.1111/2041-210X.13144",
    language: "Python",
    license: "GPL-3.0",
    properties: ["leaf-wood"],
    inputs: ["TLS"],
    year: 2019,
  },
  {
    id: "treels",
    name: "TreeLS",
    authors: "de Conto et al.",
    summary:
      "High-performance R functions for TLS point clouds: stem denoising, stem modelling, and tree taper.",
    repo: "https://github.com/tiagodc/TreeLS",
    paper: "https://doi.org/10.1016/j.compag.2017.10.019",
    language: "R",
    license: "GPL-3.0",
    properties: ["tree-stem-detection", "stem-diameter"],
    inputs: ["TLS"],
    year: 2017,
  },
  {
    id: "rtls",
    name: "rTLS",
    authors: "Guzmán et al.",
    summary:
      "Tools to voxelise TLS point clouds and derive forest-structure metrics: neighborhood features, filtering, optimal voxel size, entropy.",
    repo: "https://github.com/Antguz/rTLS",
    language: "R",
    license: "GPL-3.0",
    properties: ["qsm-branches-biomass"],
    inputs: ["TLS"],
    year: 2021,
  },
  {
    id: "rtwig",
    name: "rTwig",
    authors: "Morales & MacFarlane",
    summary:
      "Realistic QSM correction and analysis: fixes cylinder overlaps/gaps and adds twig-level detail to existing QSMs, plus box-dimension fractal analysis.",
    repo: "https://github.com/aidanmorales/rTwig",
    homepage: "https://aidanmorales.github.io/rTwig/",
    paper: "https://doi.org/10.1093/forestry/cpae046",
    language: "R",
    license: "GPL-3.0",
    properties: ["qsm-branches-biomass"],
    inputs: ["TLS"],
    year: 2024,
  },
  {
    id: "voxr",
    name: "VoxR",
    authors: "Lecigne et al.",
    summary:
      "Voxel-based 3D geometrical and morphological description of trees from unstructured TLS data: DBH, height, volume, crown diameter.",
    repo: "https://github.com/Blecigne/VoxR",
    paper: "https://doi.org/10.1093/aob/mcx095",
    language: "R",
    license: "GPL-3.0",
    properties: ["qsm-branches-biomass", "height-crown"],
    inputs: ["TLS"],
    year: 2018,
  },
  {
    id: "foresttools",
    name: "ForestTools",
    authors: "Plowright et al.",
    summary:
      "Individual tree detection and crown delineation from a canopy height model using variable-window filtering and marker-controlled watershed.",
    repo: "https://github.com/andrew-plowright/ForestTools",
    language: "R",
    license: "GPL-3.0",
    properties: ["height-crown", "tree-stem-detection"],
    inputs: ["ALS", "ULS"],
    year: 2017,
  },
  {
    id: "cloud2trees",
    name: "cloud2trees",
    authors: "Woolsey",
    summary:
      "Pipeline that extracts a full tree list, CHM, and DTM from aerial or SfM point clouds, with DBH and crown-biomass estimation via allometry.",
    repo: "https://github.com/georgewoolsey/cloud2trees",
    homepage: "https://georgewoolsey.github.io/cloud2trees/",
    language: "R",
    license: "GPL-3.0",
    properties: ["stem-diameter", "height-crown", "tree-stem-detection"],
    inputs: ["ALS", "ULS", "Photogrammetry"],
    year: 2024,
  },
  {
    id: "crownsegmentr",
    name: "crownsegmentr",
    authors: "Steinmeier et al.",
    summary:
      "R package with a C++-accelerated implementation of the AMS3D algorithm for 3D tree crown segmentation directly on airborne LiDAR points (no CHM raster required).",
    repo: "https://github.com/Lenostatos/crownsegmentr",
    language: "R",
    license: "GPL-3.0",
    properties: ["height-crown", "tree-stem-detection"],
    inputs: ["ALS"],
    year: 2025,
  },
  {
    id: "itsme",
    name: "ITSMe",
    authors: "Terryn et al.",
    summary:
      "Individual Tree Structural Metrics - derives DBH, height, volume and other structural indices from TLS point clouds and their TreeQSM models.",
    repo: "https://github.com/lmterryn/ITSMe",
    homepage: "https://lmterryn.github.io/ITSMe/",
    paper: "https://doi.org/10.1111/2041-210X.14026",
    language: "R",
    license: "MIT",
    properties: ["stem-diameter", "qsm-branches-biomass"],
    inputs: ["TLS", "MLS", "ULS"],
    year: 2023,
  },
  {
    id: "smartqsm",
    name: "SmartQSM",
    authors: "Yang et al.",
    summary:
      "Quantitative structure model using sparse-convolution-based point cloud contraction; extracts 82 multiscale architectural metrics per tree.",
    repo: "https://github.com/project-lightlin/SmartQSM",
    paper: "https://doi.org/10.1016/j.isprsjprs.2026.01.011",
    language: "Python",
    license: "AGPL-3.0",
    properties: ["qsm-branches-biomass", "stem-diameter"],
    inputs: ["TLS"],
    year: 2026,
  },
  {
    id: "pointstowood",
    name: "PointsToWood",
    authors: "Owen et al.",
    summary:
      "Deep learning leaf-wood semantic segmentation for high-resolution TLS point clouds using reflectance-modulated anisotropic convolutions.",
    repo: "https://github.com/harryjfowen/PointsToWood",
    paper: "https://arxiv.org/abs/2503.04420",
    language: "Python",
    license: "AGPL-3.0",
    properties: ["leaf-wood"],
    inputs: ["TLS"],
    year: 2025,
  },
  {
    id: "leafwood-dl",
    name: "Leaf-Wood Segmentation (qforestlab)",
    authors: "Van den Broeck et al.",
    summary:
      "Pointwise deep learning leaf-wood segmentation of tropical tree point clouds from terrestrial laser scanning, built on Open3D-ML.",
    repo: "https://github.com/qforestlab/leaf-wood-segmentation-with-deep-learning",
    paper: "https://doi.org/10.1016/j.isprsjprs.2025.06.023",
    language: "Python",
    license: "MIT",
    properties: ["leaf-wood"],
    inputs: ["TLS"],
    year: 2025,
  },
  {
    id: "treelearn",
    name: "TreeLearn",
    authors: "Henrich et al.",
    summary:
      "Fully-automatic deep-learning pipeline for individual tree instance segmentation from ground-based (TLS/MLS) forest point clouds.",
    repo: "https://github.com/ecker-lab/TreeLearn",
    paper: "https://doi.org/10.1016/j.ecoinf.2024.102888",
    language: "Python",
    license: "MIT",
    properties: ["tree-stem-detection"],
    inputs: ["TLS", "MLS"],
    year: 2024,
  },
  {
    id: "pycrown",
    name: "PyCrown",
    authors: "Zörner et al.",
    summary:
      "Fast raster-based individual tree-top detection and crown delineation from a canopy height model, accelerated with Cython/Numba.",
    repo: "https://github.com/manaakiwhenua/pycrown",
    paper: "https://doi.org/10.3390/f9110702",
    language: "Python",
    license: "GPL-3.0",
    properties: ["height-crown", "tree-stem-detection"],
    inputs: ["ALS"],
    year: 2018,
  },
  {
    id: "treegraph",
    name: "treegraph",
    authors: "Yang et al.",
    summary:
      "Builds a graph/skeleton from TLS tree point clouds and segments individual branches to generate a QSM, retrieving traits at branch and internode level.",
    repo: "https://github.com/wanxinyang/treegraph",
    paper: "https://doi.org/10.1002/rse2.399",
    language: "Python",
    license: "GPL-3.0",
    properties: ["qsm-branches-biomass", "tree-stem-detection"],
    inputs: ["TLS"],
    year: 2024,
  },
  {
    id: "treeseg",
    name: "treeseg",
    authors: "Burt et al.",
    summary:
      "Near-automatic segmentation of individual tree point clouds from larger-area forest LiDAR scans, built on PCL: stem ID, segmentation up to first branch, crown isolation.",
    repo: "https://github.com/apburt/treeseg",
    paper: "https://doi.org/10.1111/2041-210X.13121",
    language: "C++",
    license: "MIT",
    properties: ["tree-stem-detection"],
    inputs: ["TLS"],
    year: 2019,
  },
  {
    id: "computree",
    name: "Computree",
    authors: "ONF / ENSAM Cluny",
    summary:
      "Long-running collaborative C++/Qt processing platform for forest-scene point clouds (TLS and airborne); the base platform underneath SimpleForest.",
    repo: "https://github.com/computree/computree-v3",
    homepage: "https://computree.onf.fr",
    language: "C++",
    license: "GPL-3.0",
    properties: ["tree-stem-detection", "qsm-branches-biomass", "stem-diameter"],
    inputs: ["TLS", "ALS"],
    year: 2010,
  },
  {
    id: "optqsm",
    name: "optqsm",
    authors: "Burt",
    summary:
      "Wraps TreeQSM to fully automate QSM construction by analyzing point-neighbor distances to auto-select input parameters per tree.",
    repo: "https://github.com/apburt/optqsm",
    language: "MATLAB",
    license: "MIT",
    properties: ["qsm-branches-biomass"],
    inputs: ["TLS"],
    year: 2020,
  },
  {
    id: "dft",
    name: "Digital Forestry Toolbox",
    authors: "Parkan",
    summary:
      "Matlab/Octave toolbox for airborne forestry remote sensing: DTM/DSM/CHM generation, watershed-based individual tree crown detection, canopy metrics.",
    repo: "https://github.com/mparkan/Digital-Forestry-Toolbox",
    homepage: "https://mparkan.github.io/Digital-Forestry-Toolbox/",
    paper: "https://doi.org/10.5281/zenodo.1213013",
    language: "MATLAB",
    license: "GPL-3.0",
    properties: ["height-crown", "tree-stem-detection"],
    inputs: ["ALS"],
    year: 2018,
  },
  {
    id: "pointcloudtools",
    name: "Point-Cloud-Tools",
    authors: "Yrttimaa et al.",
    summary:
      "Automatic MATLAB tools to characterize trees from TLS point clouds: crown detection, stem/crown classification, stem metrics and dendrometry.",
    repo: "https://github.com/tuomasyr/Point-Cloud-Tools",
    paper: "https://doi.org/10.3390/rs11121423",
    language: "MATLAB",
    license: "CC-BY-4.0",
    properties: ["stem-diameter", "height-crown", "qsm-branches-biomass"],
    inputs: ["TLS"],
    year: 2019,
  },
];
